
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT UNIQUE,name TEXT,role TEXT,password_hash TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS experts (id TEXT PRIMARY KEY,user_id TEXT,title TEXT,bio TEXT,rate_per_min_cents INTEGER DEFAULT 200,is_online INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS chats (id TEXT PRIMARY KEY,user_id TEXT,expert_id TEXT,status TEXT DEFAULT 'open',created_at TEXT DEFAULT CURRENT_TIMESTAMP,per_min_cents INTEGER DEFAULT 200);
CREATE TABLE IF NOT EXISTS messages (id TEXT PRIMARY KEY,chat_id TEXT,sender_type TEXT,content TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
